‘Aasaan’ : ‘easy’,
‘aasan’ : ‘easy’,
‘adh’ : ‘half’,
‘adh-bharyal’ : ‘not filled’,
‘afwah’ : ‘doubtful news’,
‘afwahan’ : ‘doubtful news’,
‘afwahn’ : ‘doubtful news;,
‘ahtejaj’ : ‘protest’,
‘ameen’ : ‘honest’,
‘amin’ : ‘honest’,
‘asaan’ : ‘easy’,
‘barbad’ : ‘destroy’,
‘bchraee’ : ‘bad’,
‘bdkaaree’ : 'wrong doings',
‘bdkaari’ : 'wrong doings',
‘bdkaree’ : 'wrong doings',
‘bdkari’ : 'wrong doings',
‘bdnaam’ : ‘notorous’,
‘bdnam’ : ‘notorous’,
‘bdtameezee’ : ‘rude ’,
‘bdtameezi’ : ‘rude ’,
‘bdtamizee’ : ‘rude ’,
‘bdtamizi’ : ‘rude ’,
‘bdtar’ : ‘worse’,
‘bdtr’ : ‘worse’,
‘bdtreen’ : ‘worst’,
‘beemaar’ : ‘sick’,
‘beemar’ : ‘ill’,
‘behtr’ : ‘better’,
‘bekaar’ : ‘useless’,
‘bekar’ : ‘useless’,
‘bemar’ : ‘ill’,
‘berbad’ : ‘destroy’,
‘bewakoofee’ : ‘stupid’,
‘bewakoofi’ : ‘stupid’,
‘Bewaqoof’ : ‘stupid’
‘bewaqoofi’ : ‘stupid’,
‘bewkoofi’ : ‘stupid’,
‘bhalai’ : ‘good’,
‘bhalo’ : ‘good’,
‘bhariyal’ : ‘filled’,
‘bharyal’ : ‘filled’,
‘bhtr’ : ‘better,
‘brbaad’ : ‘destroy’,
‘brbad’ : ‘destroy’,
‘buchhraee’ : ‘bad’,
‘buchhrai’ : ‘bad’,
‘buchhro’ : ‘bad’,
‘budnam’ : ‘notorous’,
‘buro’ : ‘bad’,
‘burrai’ : ‘bad’,
‘burro’ : ‘bad’,
‘chango’ : ‘good’,
‘chhurwagee’ : ‘ ’,
‘chhurwagi’ : ‘ ‘,
‘dadho’ : ‘very’,
‘Dharai’ : ‘slow’,
‘dharo’ : ‘slow’,
‘dhoko’ : ‘deceive’,
‘dhro’ : ‘slow’,
‘dubro’ : ‘weak’
'dunya': 'world',
‘emandar’ : ‘honest’,
‘faedemand’ : ‘beneficial’,
‘faedemand’ : ‘useful’,
‘faedo’ : ‘benefit’,
‘faedo’ : ‘useful’,
‘faidemand’ : ‘useful’,
‘faraib’ : ‘not true’,
‘fareb’ : ‘not true’,
‘fraib’ : ‘not true’,
‘freb’ : ‘not true’,
‘fuzol’ : ‘useless’
‘fuzool’ : ‘useless’,
‘fzool’ : ‘useless’,
‘galat’ : ‘wrong’,
‘ger mutmaen’ : ‘not satisfied’,
‘ghane’ : ‘more’,
‘ghaney’ : ‘more’,
‘ghano’ : ‘more’,
‘ghne’ : ‘more’,
‘ghney’ : ‘more’,
‘glt’ : ‘wrong’,
‘gso’ : ‘anger’,
‘guso’ : ‘anger’,
‘hathee’ : ‘help’,
‘hathee’ : ‘kind’,
‘hathi’ : ‘kind’,
‘hthee’ : ‘kind’,
‘ihtjaj’ : ‘protest’,
‘ikhlak’ : ‘moral’,
‘ikhlaq’ : ‘moral’,
'intrnet':'Internet',
‘istemaal’ : ‘use’,
‘istemal’ : ‘use’,
‘kachee’ : ‘not certain’,
‘kachi’ : ‘not certain’,
‘kamzor’ : ‘weak’,
‘karro’ : ‘bitter’,
‘kawar’: ‘anger’,
‘kawr’ : ‘anger’,
‘kchee’ : ‘not certain’,
‘kchi’ : ‘not certain’,
‘khalee’ : ‘empty’,
‘khali’ : ‘empty’,
‘khbsorat’ : ‘beautiful’,
‘khobsoorat’ : ‘beautiful’,
‘khoobsoorat’ : ‘beautiful’,
‘khoobsorat’ : ‘beautiful’,
‘khush’ : ‘happy’,
‘khuwaar’ : ‘notorous’,
‘khuwar’ : ‘notorous’,
‘khuwari’ : ‘notorous’,
‘khwar’ : ‘notorous’,
‘kino’ : ‘bad’,
‘kmzor’ : ‘weak’,
‘knno’ : ‘bad’,
‘krro’ : ‘bitter’,
‘magan’ : ‘ un aware‘ ,
‘maggan’ : ‘un aware',
'manrhon': 'people',
‘mast’ : ‘un aware ‘,
‘mathae’ : ‘bad’,
‘mathe’ : ‘high’,
‘mathabharo’ : ‘high’,
‘mathahein’ : ‘high’,
‘maatho’ : ‘not good’,
'mazboot' : 'strong',
'medya':'media',
‘mgn’ : ‘un aware ‘,
‘mst’ : ‘un aware ‘ ,
‘mukamal’ : ‘complete’,
‘munasib’ : ‘suitable’,
‘na aahe’ : ‘not’,
‘na aahey’ : ‘not’,
‘na ahe’ : ‘not’,
‘na mukamal’ : ‘not complete’,
‘na mukamil’ : ‘not complete’,
‘naakari’ : ‘negative’,
‘naas’ : ‘destroy’,
‘naass’ : ‘destroy’,
‘nabal’ : ‘weak’,
‘nahe’ : ‘not’,
'na aahe':'not',
‘nahey’ : ‘not’,
‘nakhush’ : ‘unhappy’,
‘naklee’ : ‘artificial’,
‘nakli’ : ‘artificial’,
‘nass’ : ‘destroy’,
‘nbl’ : ‘weak’,
‘nikamo’ : ‘useless’,
‘nikmo’ : ‘useless’,
‘nklee’ : ‘artificial’,
‘nkli’ : ‘artificial’,
‘ootak’ : ‘drawing room’,
‘ootakoo’ : ‘drawing room’,
‘ootaque’ : ‘place’,
‘pastee’ : ‘come down’,
‘pkee’ : ‘certain’,
‘pki’ : ‘certain’,
‘pkk’ : ‘certain’,
‘pkkee’ : ‘certain’,
‘pkki’ : ‘certain’,
‘pkky’ : ‘certain’,
‘prskoon’ : ‘satisfied’,
‘pstee’ : ‘come down’,
‘pursukoon’ : ‘satisfied’,
‘qareeb’ : ‘near’,
‘qreeb’ : ‘near’,
'rabta' : 'connections',
'rabto' : 'connection',
‘rahat’ : ‘’,
‘raht’ : '',
'sabh; : 'all',
‘sahe’ : ‘right’,
‘sahee’ : ‘right’,
‘sahi’ : ‘right’,
‘savalo’ : ‘easy’,
'soshal':'social',
‘shee’ : ‘right’,
‘sheedaee’ : ‘’,
‘sheedai’ : ‘’,
‘suhnee’ : ‘beautiful’
‘suhno’ : ‘handsome’,
'sust':'lazy',
‘suthee’ : ‘nice’,
‘sutho’ : ‘good’,
‘tabah’ : ‘destroy‘ ,
‘taqatwar’ : ‘powerful’,
‘taqatwer’ : ‘powerful’,
‘taqatwr’ : ‘powerful’,
‘taqtwar’ : ‘powerful’,
‘taqtwr’ : ‘powerful’,
‘taraj’ : ‘destroy‘ ,
‘taskeen’ : ‘satisfied’,
‘tbaah’ : ‘destroy‘,
‘tbah’ : ‘destroy‘ ,
‘tez’ : ‘fast’,
‘thoro’ : ‘less’,
‘tskeen’ : ‘satisfied’,
‘un-bharyal’ : ‘empty’,
‘waddo’ : ‘big’,
‘wadhao’ : ‘ ‘,
‘wado’ : ‘big’,
'wqt':'time',
‘weeran’ : ‘destroy‘ ,
‘ziada’ : ‘much’,
‘ziyaan’ : ‘waster’,
‘ziyan’ : ‘waste’,
‘zyaan’ : ‘waste’,
‘zyan’ : ‘waste’
