rssw = [aa, aahe, aahein, aahin, aahya, aahyou, aayal,
aayus, aein, aen, ag, ahe, aj, ajoko,
andr, asa, asa’an, asanjo, awha, awha’an, b, 
ba’ad, baabat, baad, baahr, bae, bannjee, bannji, barsa, 
bdra, beehr, bna, bnd, bya, chhadee,
dafo, deh, dno, doraan, doran, ehra, enda,
endr, g, gad, ghurje, ghurjey, hale, hali,
halya, halyo, hea, hee, heth, hin, hitey,  
hk, ho, hoa, hoo, hoyus, hr, Hrr,
hua, hue, hun, hunan, hutey, huyus, ihe,
ilaawa, ilawa, in, inhan, istemaal, ita’an, ja,  
jadahn, jadhahein, jaree, jari, je, jee, jein,  
jekr, jenh, jestaein, jita’an, jiya’an, jn, jo,
kadahn, kae, kalh, kaya, kayo, kea,  
kehri, kehro, kenh, kenh, ker, ketra, kha,  
khe, khud, kithe, kn, Kndo, ko, koe,  
kre, kujh, kya, lae, lagae, maa, marhoo,
marhun, matha, me, mein, milando, milo, milya,
milyo, milyou, mokhe, mou’n, muhjo, mukhe, na,
ohe, paan, pehja, poe, pr, pya, rahan,
rahe, rahya, rahyo, sa, sa’an, sabh, saghan,  
saghe, saghein, saghje, saghjey, sagya, samho, sandn,
sands, sbhn, sghn, so, srf, ta, ta’an,
te, tenh, tey, tha, thee, tho, thyan,
tn, tou, touhjo, trfa, tuhjo, twha, uhe,  
un, unhan, unhn, uta’an, varto, vathe, vathn,
vathno, vato, vayun, vijhan, wadheek, wae, waee,
wagherah, wara, waree, waro, warto, wat, wathan,
wato, wich, ya, ya’an]

